apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../helm-guestbook

helmCharts:
- name: helm-guestbook
  version: 0.1.0
  releaseName: helm-guestbook-prod
  namespace: guestbook
  valuesFile: https://raw.githubusercontent.com/codefresh-contrib/argocd-guestbook-environments/main/production/guestbook/values.yaml