apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
chuck: failing
helmGlobals:
  chartHome: ../..
helmCharts:
  - name: helm-guestbook
    releaseName: helm-guestbook-dev
    namespace: guestbook
    valuesFile: https://raw.githubusercontent.com/codefresh-contrib/argocd-guestbook-environments/d79c4a3fd6af27fb4efe0186b3e0f3f391000435/development/guestbook/values.yaml
