apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmGlobals:
  chartHome: ../..
helmCharts:
  - name: helm-guestbook
    releaseName: helm-guestbook-dev
    namespace: guestbook
    valuesFile: https://raw.githubusercontent.com/codefresh-contrib/argocd-guestbook-environments/7b4652788d814223fe1a10d32132cd944de48553/development/guestbook/values.yaml
