apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
chuck: failing
helmGlobals:
  chartHome: ../..
helmCharts:
  - name: helm-guestbook
    releaseName: helm-guestbook-dev
    namespace: guestbook
    valuesFile: https://raw.githubusercontent.com/codefresh-contrib/argocd-guestbook-environments/83a2d460cc61a35bc02a6b1d3b562b35ac2b66d7/development/guestbook/values.yaml
