apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmGlobals:
  chartHome: ../..
helmCharts:
  - name: helm-guestbook
    releaseName: helm-guestbook-dev
    namespace: guestbook
    valuesFile: https://raw.githubusercontent.com/codefresh-contrib/argocd-guestbook-environments/91497f9ff73f3b222195cf66e2a1987aaba6c67e/development/guestbook/values.yaml
