apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmGlobals:
  chartHome: ../..
helmCharts:
  - name: helm-guestbook
    releaseName: helm-guestbook-stage
    namespace: guestbook
    valuesFile: https://raw.githubusercontent.com/codefresh-contrib/argocd-guestbook-example-apps/45f661b12a435cd6c8e69ebaed76518c5a2d0ee8/staging/guestbook/values.yaml
