apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmGlobals:
  chartHome: ../..
helmCharts:
  - name: helm-guestbook
    releaseName: helm-guestbook-stage
    namespace: guestbook
    valuesFile: https://raw.githubusercontent.com/codefresh-contrib/{{ inputs.parameters.REPO_NAME
      }}/3aa85a2af638a04e7fa76f8a92d44f3f22aa0e58/staging/guestbook/values.yaml
