apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmGlobals:
  chartHome: ../..
helmCharts:
  - name: helm-guestbook
    releaseName: helm-guestbook-stage
    namespace: guestbook
    valuesFile: https://raw.githubusercontent.com/codefresh-contrib/argocd-guestbook-environments/c1ed7523503bed8f7d1219ec4a9465d0dc31e2bc/staging/guestbook/values.yaml
